services:
  - type: web
    name: tds-virtual-ta-api
    runtime: python
    region: oregon  # or choose another region like frankfurt, singapore, etc.
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: free
